### ISSUE TITLE
conda-forge needs to update jpeg lib to 9b for win64 platform

### ISSUE THREAD

**Issue by shelper** [conda-forge/jpeg-feedstock#5]
conda-forge has jpeg9 for 32bit, but not 64bit,
at least on my windows 7 64bit, when i tried conda install -c conda-forge jepg it only installs version 8d
see below:

> jpeg 9b vc10_0
> 
> file name : conda-forge::jpeg-9b-vc10_0.tar.bz2
> name : jpeg
> version : 9b
> build number: 0
> build string: vc10_0
> channel : conda-forge/win-64
> size : 297 KB
> arch : x86_64
> binstar : {'package_id': '57113611752ed06038dfe854', 'owner_id': '5528f42ce1dad12
> 974506e8d', 'channel': 'main'}
> features : vc10
> fn : jpeg-9b-vc10_0.tar.bz2
> license : Custom free software license
> machine : x86_64
> md5 : 16d13c0ff3f70aeb3985c41e90a9889b
> operatingsystem: win32
> platform : win
> priority : 2
> schannel : conda-forge
> subdir : win-64
> target-triplet: x86_64-any-win32
> url : https://conda.anaconda.org/conda-forge/win-64/jpeg-9b-vc10_0.tar.bz2
> dependencies:
> 
> jpeg 9b vc14_0
> 
> file name : conda-forge::jpeg-9b-vc14_0.tar.bz2
> name : jpeg
> version : 9b
> build number: 0
> build string: vc14_0
> channel : conda-forge/win-64
> size : 301 KB
> arch : x86_64
> binstar : {'package_id': '57113611752ed06038dfe854', 'owner_id': '5528f42ce1dad12
> 974506e8d', 'channel': 'main'}
> features : vc14
> fn : jpeg-9b-vc14_0.tar.bz2
> license : Custom free software license
> machine : x86_64
> md5 : 84096b1f3fddf28e165117590fcad7b4
> operatingsystem: win32
> platform : win
> priority : 2
> schannel : conda-forge
> subdir : win-64
> target-triplet: x86_64-any-win32
> url : https://conda.anaconda.org/conda-forge/win-64/jpeg-9b-vc14_0.tar.bz2
> dependencies:
> 
> jpeg 9b vc9_0
> 
> file name : conda-forge::jpeg-9b-vc9_0.tar.bz2
> name : jpeg
> version : 9b
> build number: 0
> build string: vc9_0
> channel : conda-forge/win-64
> size : 294 KB
> arch : x86_64
> binstar : {'package_id': '57113611752ed06038dfe854', 'owner_id': '5528f42ce1dad12
> 974506e8d', 'channel': 'main'}
> features : vc9
> fn : jpeg-9b-vc9_0.tar.bz2
> license : Custom free software license
> machine : x86_64
> md5 : b73350bd1d7e5381760ab5e9bf4edb58
> operatingsystem: win32
> platform : win
> priority : 2
> schannel : conda-forge
> subdir : win-64
> target-triplet: x86_64-any-win32
> url : https://conda.anaconda.org/conda-forge/win-64/jpeg-9b-vc9_0.tar.bz2
> dependencies:

**Comment by ocefpaf** [comment]
The files do exist. See https://anaconda.org/conda-forge/jpeg/files

The preference for `jpeg 8*` is due to the vc package being in conflict with `jpeg 9*`. That is quite odd and I never saw that before. I will look into it.

Just try to force install jpeg 9 with `conda install jpeg=9b` and you will see the error message.

**Comment by shelper** [comment]
i tried and below is what i have

> conda install jpeg=9b
> Using Anaconda API: https://api.anaconda.org
> Fetching package metadata ...........
> Solving package specifications: ....
> 
> The following specifications were found to be in conflict:
> jpeg 9b*
> Use "conda info <package>" to see the dependencies for each package.

how you conlude from that it is due to the vc package?
hope you can help to solve the problem, thanks!

**Comment by ocefpaf** [comment]
> how you conclude from that it is due to the vc package?

On my Windows VM I got a `vc` conflict message. To be honest I don't think this has anything to do with `vc`. I can install `jpeg 9*` on my root env but not on any new env. @msarahan any idea of what may be happening here?

**Comment by msarahan** [comment]
You have to have a way of activating the vc feature somehow.  Installing a particular vc package would work.  Python would also work.  You cannot install JPEG completely by itself on Windows.

**Comment by ocefpaf** [comment]
I saw that @gillins changed `gdal` to use `vc` and I never bother to check here. Even though `conda-smithy rerender` is broken maybe we should start updating this recipes to be more like https://github.com/conda-forge/gdal-feedstock/commit/36aaf09c94043360b78348f5b6dbc20e3812b293

**Comment by jakirkham** [comment]
I'd like to hold off on switching to `vc` until we have handled the Travis CI image switch (which is still not done). Switching to `vc` has been a nightmare with re-rendering on the `tk` feedstock (even with people who know what to expect). Am not eager to explore it with more feedstocks with so many re-renderings still to do.

Would be happy to explore it after `conda-build-all` and/or `conda-build` have implemented what is necessary for it to work and `conda-smithy` is able to use this. As this will probably require some testing and exploration, it may even be good to table this until after the `conda-build` 2.0.x switch so that we don't have any more big changes staring us down while doing that exploration.

**Comment by jakirkham** [comment]
> You have to have a way of activating the vc feature somehow. Installing a particular vc package would work. Python would also work. You cannot install JPEG completely by itself on Windows.

In short, are you asking @shelper to pick a Python version or `vc` version to install with `jpeg` to ensure it gets the feature too, @msarahan ? If so, would you mind trying this @shelper and seeing if that works?

**Comment by shelper** [comment]
what i have is python 3.5 installed with the most updated anaconda for windows 64 bit, and I have vs-community 2015 installed  as well. @jakirkham i dont fully understand your words about " pick a python version or vc version to install with jpeg", i am a newbie to conda forge.

**Comment by ocefpaf** [comment]
> I dont fully understand your words about " pick a python version or vc version to install with jpeg", i am a newbie to conda forge.

Do not feel bad for not understanding that. The technologies are working against you here and demanding more than they should. If you do `conda create -n TEST -c conda-forge jpeg --yes` it should fail because conda does not know which `vc` (The Microsoft visual studio run time) needs to be installed. That depends on the Python version. So you have to change that to `conda create -n TEST -c conda-forge jpeg python=2.7 --yes` to make it work. (Or any other python version or even the `vc` package itself. Although I find it easier to specify a python version.)

**Comment by jakirkham** [comment]
Sorry that was terse @shelper . I think @ocefpaf did a very nice job of laying it out. Though if you have more questions, please ask.
